version: '3.4'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - '80'

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - '8080'
