permissions:
  contents: read

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  workflow_dispatch:

jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Corepack
        run: corepack enable
      - name: Setup Node v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install Yarn dependencies
        run: yarn install --immutable
      - name: ESLint
        run: yarn run lint
      - name: Prettier
        run: yarn run format
